version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    mem_limit: 1g
